[project]
name = "langgraph-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "poethepoet>=0.37.0",
]
[tool.poe.tasks]
run = "python main.py"
